name: MysqlInventoryBridge
main: ca.matai.crossinvent.inventory.Inv
version: 2.4.1
author: CraftersLand
load: STARTUP
api-version: 1.16
description: Sync players inventorys over many servers using MySQL.
softdepend: [ProtocolLib]